### ISSUE TITLE
Double SandboxStateSandboxReady notification on startup

### ISSUE THREAD

**Issue by saqsun** [koreezgames/phaser-particle-editor#78]
@RollinSafary is this normal or its a bug?

**Comment by saqsun** [comment]
@RollinSafary also please rename SandboxStateSandboxReady to SandboxStateReady

**Comment by RollinSafary** [comment]
notifications were different but were look alike, so i've renamed notifications not to confuse anymore

**SandboxStateSandboxReady** renamed to **SandboxReady**
**SandboxStateStateReady** renamed to **SandboxStateReady**
